version: '3.5'

services:

  node-docker:
    container_name: node-docker-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/Users/vamsee/practicess/nodeDocker'
      - '/Users/vamsee/practicess/nodeDocker/node_modules'
    ports:
      - '9000:9000'
    links:
      - database
    environment:
      MONGO_DB_ADDRESS: database
      MONGO_DB_PORT: 27017
      NODE_ENV: docker
      TRACE_REQ: "true"

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
    - "27017:27017" # specify port forwarding
